
///
/// ApplicationWindow signal enums
/// 
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum ApplicationWindowConnections
{

    AccessibleRoleNotify, //https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/stable/latest/docs/libadwaita/struct.ApplicationWindow.html
    ContentNotify,        //https://world.pages.gitlab.gnome.org/Rust/libadwaita-rs/stable/latest/docs/libadwaita/prelude/trait.AdwApplicationWindowExt.html
    ActivateDefault,      //https://gtk-rs.org/gtk4-rs/stable/0.4/docs/gtk4/prelude/trait.GtkWindowExt.html
    ActivateFocus,
    CloseRequest,
    EnableDebugging,
    KeysChanged,
    ApplicationNotify,
    ChildNotify,
    DecoratedNotify,
    DefaultHeightNotify,
    DefaultWidgetNotify,
    DefaultWidthNotify,
    DeletableNotify,
    DestroyWithParentNotify,
    DisplayNotify,
    FocusVisibleNotify,
    FocusWidgetNotify,
    FullscreenedNotify,
    HandleMenubarAccelNotify,
    HideOnCloseNotify,
    IconNameNotify,
    IsActiveNotify,
    MaximizedNotify,
    MnemonicsVisibleNotify,
    ModalNotify,
    ResizableNotify,
    StartupIdNotify,
    TitleNotify,
    TitlebarNotify,
    TransientForNotify,
    Destroy,   //https://gtk-rs.org/gtk4-rs/stable/0.4/docs/gtk4/prelude/trait.WidgetExt.html
    DirectionChanged,
    Hide,
    KeynavFailed,
    Map,
    MnemonicActivate,
    MoveFocus,
    QueryTooltip,
    Realize,
    Show,
    StateFlagsChanged,
    Unmap,
    Unrealize,
    CanTargetNotify,
    CssClassesNotify,
    CursorNotify,
    FocusOnClickNotify,
    FocusableNotify,
    HalignNotify,
    HasDefaultNotify,
    HasFocusNotify,
    HasTooltipNotify,
    HeightRequestNotify,
    HexpandNotify,
    HexpandSetNotify,
    LayoutManagerNotify,
    MarginBottomNotify,
    MarginEndNotify,
    MarginStartNotify,
    MarginTopNotify,
    NameNotify,
    OpacityNotify,
    OverflowNotify,
    ParentNotify,
    ReceivesDefaultNotify,
    RootNotify,
    ScaleFactorNotify,
    SensitiveNotify,
    TooltipMarkupNotify,
    TooltipTextNotify,
    ValignNotify,
    VexpandNotify,
    VexpandSetNotify,
    VisibleNotify,
    WidthRequestNotify

}

